openapi: "3.0.3"
info:
  version: 0.1.0
  title: Common API models for OpenHES
  description: Common API models for OpenHES
  license:
    name: BSL-1.0
    url: https://opensource.org/licenses/BSL-1.0
  contact:
    name: Cybros Labs team
    email: info@cybroslabs.com
    url: https://www.cybroslabs.com/index-en.html

components:
  schemas:
    GenericObject: {}

    DriverSpecSchema:
      type: object
      description: >
        Schema containing communication driver spec.
      example:
        driverType: "CYBROSLABS_MAGEMETER_DLMS"
        version: "v1.2.3"
      required:
        - driverType
        - version
      properties:
        driverType:
          type: string
          description: >
            The driver type identifier.
        version:
          type: string
          description: >
            The version of the driver.

    DriverSchema:
      type: object
      description: >
        Schema that describes communication driver details.
      example:
        spec:
          driverType: "CYBROSLABS_MAGEMETER_DLMS"
          version: "v1.2.3"
      properties:
        spec:
          $ref: "#/components/schemas/DriverSpecSchema"

    DriverActionAttributeSchema:
      type: object
      description: >
        Schema that describes driver action attributes.
      example:
        type: GET_REGISTER
        attributes:
          - name: "A+"
            description: "Register A+"
            type: STRING
            mandatory: true
            defaultValue: "0-0:1.8.0.255"
          - name: "A-"
            description: "Register A-"
            type: STRING
            mandatory: false
            defaultValue: "0-0:2.8.0.255"
      properties:
        type:
          $ref: "../job/job.yaml#/components/schemas/ActionTypeSchema"
        attributes:
          $ref: "#/components/schemas/DriverAttributesSchema"

    DriverCommunicationTemplateSchema:
      type: object
      description: >
        Schema that describes the communication template.
      properties:
        type:
          type: string
          description: >
            The type of the communication template.
        datalinkTemplates:
          $ref: "#/components/schemas/DriverDatalinkTemplateSchemas"

    DriverDatalinkTemplateSchemas:
      type: array
      description: >
        The list of datalink templates valid for the communication template.
      items:
        $ref: "#/components/schemas/DriverDatalinkTemplateSchema"

    DriverDatalinkTemplateSchema:
      type: object
      description: >
        Schema that describes the datalink template.
      properties:
        linkProtocol:
          type: string
          description: >
            The link protocol.
        appProtocols:
          $ref: "#/components/schemas/DriverAppProtocolsSchema"

    DriverAppProtocolsSchema:
      type: array
      description: >
        The list of application protocols valid for the datalink template.
      items:
        $ref: "#/components/schemas/DriverAppProtocolSchema"

    DriverAppProtocolSchema:
      type: object
      description: >
        Schema that describes the application protocol.
      properties:
        protocol:
          type: string
          description: >
            The application protocol.
        profile:
          $ref: "#/components/schemas/DriverAttributesSchema"

    DriverAttributesSchema:
      type: array
      description: >
        Schema that describes a list of attributes supported by a driver.
      example:
        - name: "register"
          description: "Some register."
          type: STRING
          mandatory: true
          defaultValue: "0-0:1.8.0.255"
      items:
        $ref: "#/components/schemas/AttributeDefinitionSchema"

    AttributeDefinitionSchema:
      type: object
      description: >
        Schema that describes a driver attribute.
      example:
        name: "register"
        description: "The register to get."
        type: STRING
        mandatory: true
        defaultValue: "0-0:1.8.0.255"
      properties:
        name:
          type: string
          description: >
            The name of the attribute.
        description:
          type: string
          description: >
            The description of the attribute.
        type:
          type: string
          enum:
            - STRING
            - INTEGER
            - NUMBER
            - BOOLEAN
            - BINARY
          description: >
            The type of the attribute.
              * `STRING` - The attribute is a string.
              * `INTEGER` - The attribute is an integer.
              * `NUMBER` - The attribute is a decimal number.
              * `BOOLEAN` - The attribute is a boolean.
              * `BINARY` - The attribute is a binary.
        mandatory:
          type: boolean
          description: >
            Indicates whether the attribute is mandatory or not.
        defaultValue:
          $ref: "#/components/schemas/GenericObject"
