openapi: "3.0.3"
info:
  version: 0.1.0
  title: Common API models for OpenHES
  description: Common API models for OpenHES
  license:
    name: BSL-1.0
    url: https://opensource.org/licenses/BSL-1.0
  contact:
    name: Cybros Labs team
    email: info@cybroslabs.com
    url: https://www.cybroslabs.com/index-en.html

components:
  schemas:
    GenericObject: {}

    DriverSchema:
      type: object
      description: >
        Schema that describes communication driver details.
      example:
        spec:
          image: "docker.example.com/example/driver/cybroslabs-magemeter-dlms:v1"
          resources:
            limits:
              cpu: 1
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
      properties:
        spec:
          $ref: "#/components/schemas/DriverSpecSchema"

    DriverImagePullSecretsSchema:
      type: object
      description: >
        Schema that describes the image pull secrets for a driver. If dockerconfigjson is not provided, the secret must already exist in the cluster.
      example:
        name: "my-image-pull-secrets"
        dockerconfigjson: "eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiaWFtIiwicGFzc3dvcmQiOiJnaHBfbWFnaWNzdHJpbmciLCJlbWFpbCI6ImlhbUBleGFtcGxlLmNvbSIsImF1dGgiOiJhV0Z0T21kb2NGOXRZV2RwWTNOMGNtbHVadz09In19fQ=="
      required:
        - name
      properties:
        name:
          type: string
          description: >
            The name of the image pull secret.
        dockerconfigjson:
          type: string
          description: >
            The base64 encoded docker config json for the image pull secret.

    DriverSpecSchema:
      type: object
      description: >
        Schema that registers new or updates already registered communication drivers.
      example:
        image: "docker.example.com/example/driver/cybroslabs-magemeter-dlms:v1"
        resources:
          limits:
            cpu: 1
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      required:
        - image
        - resources
      properties:
        imagePullSecrets:
          $ref: "#/components/schemas/DriverImagePullSecretsSchema"
        image:
          type: string
          pattern: "^[a-zA-Z0-9-.]+(:[0-9]+)?[a-zA-Z0-9/]+(:[a-zA-Z0-9-]+|@sha256:[0-9a-f]+)?"
          example: "docker.example.com/example/driver/cybroslabs-magemeter-dlms:v1 (or using digest @sha256:1234567890abcdef)"
        resources:
          $ref: "../../k8s/containers/containers.yaml#/components/schemas/ContainerResourcesSetSchema"

    DriverStatusSchema:
      type: object
      description: >
        Schema that describes the status of a driver.
      example:
        driverType: "CYBROSLABS_MAGEMETER_DLMS"
      required:
        - driverType
      properties:
        driverType:
          type: string
          pattern: "^[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9]$"
          example: "CYBROSLABS_MAGEMETER_DLMS"

    DriverDetailsSchema:
      type: object
      description: >
        Schema that describes communication driver details.
      example:
        spec:
          image: "docker.example.com/example/driver/cybroslabs-magemeter-dlms:v1"
          resources:
            limits:
              cpu: 1
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
        status:
          driverType: "CYBROSLABS_MAGEMETER_DLMS"
      allOf:
        - $ref: "#/components/schemas/DriverSchema"
        - type: object
          properties:
            status:
              $ref: "#/components/schemas/DriverStatusSchema"

    DriverActionAttributeSchema:
      type: object
      description: >
        Schema that describes driver action attributes.
      example:
        type: GET_REGISTER
        attributes:
          - name: "A+"
            description: "Register A+"
            type: STRING
            mandatory: true
            defaultValue: "0-0:1.8.0.255"
          - name: "A-"
            description: "Register A-"
            type: STRING
            mandatory: false
            defaultValue: "0-0:2.8.0.255"
      properties:
        type:
          $ref: "../job/job.yaml#/components/schemas/ActionTypeSchema"
        attributes:
          $ref: "#/components/schemas/DriverAttributesSchema"

    DriverAttributesSchema:
      type: array
      description: >
        Schema that describes a list of attributes supported by a driver.
      example:
        - name: "register"
          description: "Some register."
          type: STRING
          mandatory: true
          defaultValue: "0-0:1.8.0.255"
      items:
        $ref: "#/components/schemas/AttributeDefinitionSchema"

    AttributeDefinitionSchema:
      type: object
      description: >
        Schema that describes a driver attribute.
      example:
        name: "register"
        description: "The register to get."
        type: STRING
        mandatory: true
        defaultValue: "0-0:1.8.0.255"
      properties:
        name:
          type: string
          description: >
            The name of the attribute.
        description:
          type: string
          description: >
            The description of the attribute.
        type:
          type: string
          enum:
            - STRING
            - INTEGER
            - NUMBER
            - BOOLEAN
            - BINARY
          description: >
            The type of the attribute.
              * `STRING` - The attribute is a string.
              * `INTEGER` - The attribute is an integer.
              * `NUMBER` - The attribute is a decimal number.
              * `BOOLEAN` - The attribute is a boolean.
              * `BINARY` - The attribute is a binary.
        mandatory:
          type: boolean
          description: >
            Indicates whether the attribute is mandatory or not.
        defaultValue:
          $ref: "#/components/schemas/GenericObject"
