module-title = "OpenHES API"
input-descriptor-file = "protobuf/pbapi/pbapi.pb"
output-dir = "protobuf/pbapi/docs"
hidden-packages = ["google.protobuf"]
footer-content = "© 2025 cybros labs"
main-page-content-file = "docs-index.md"
