openapi: "3.0.3"
info:
  version: 0.1.0
  title: Common API models for OpenHES
  description: Common API models for OpenHES
  license:
    name: BSL-1.0
    url: https://opensource.org/licenses/BSL-1.0
  contact:
    name: Cybros Labs team
    email: info@cybroslabs.com
    url: https://www.cybroslabs.com/index-en.html

components:
  schemas:
    CommunicationUnitID:
      type: string
      description: >
        The ID of the communication unit. The ID must be unique across all OpenHES components.
      format: uuid

    DeviceID:
      type: string
      description: >
        The ID of the device. The ID must be unique across all OpenHES components.
      format: uuid

    DeviceGroupID:
      type: string
      description: >
        The ID of the device group. The ID must be unique across all OpenHES components.
      format: uuid

    CommunicationUnitSchema:
      type: object
      description: >
        Schema that describes communication unit details.
      properties:
        id:
          $ref: "#/components/schemas/CommunicationUnitID"
        externalID:
          type: string
          description: >
            The public ID of the communication unit.
          nullable: true
        name:
          type: string
          description: >
            The name of the communication unit.
          minLength: 1
        connectionInfo:
          $ref: "../job/job.yaml#/components/schemas/ConnectionTypeSchema"
      required:
        - id
        - name
        - connectionInfo

    CommunicationUnitListID:
      type: array
      description: >
        The list of communication unit IDs.
      items:
        $ref: "#/components/schemas/CommunicationUnitID"

    DeviceSchema:
      type: object
      description: >
        Schema that describes device details.
      properties:
        id:
          $ref: "#/components/schemas/DeviceID"
        externalID:
          type: string
          description: >
            The public ID of the device.
          nullable: true
        name:
          type: string
          description: >
            The name of the device.
          minLength: 1
        communicationUnitID:
          $ref: "#/components/schemas/CommunicationUnitListID"
        attributes:
          $ref: "../job/job.yaml#/components/schemas/AttributesSchema"
        timezone:
          type: string
          description: >
            The timezone of the device.
          nullable: true
      required:
        - id
        - name
        - communicationUnitID
        - attributes

    DeviceGroupSchema:
      type: object
      description: >
        Schema that describes device group details.
      properties:
        id:
          $ref: "#/components/schemas/DeviceGroupID"
        externalID:
          type: string
          description: >
            The public ID of the device group.
          nullable: true
        name:
          type: string
          description: >
            The name of the device group.
          minLength: 1
      required:
        - id
        - name
