openapi: "3.0.3"
info:
  version: 0.1.0
  title: Common API models for OpenHES
  description: Common API models for OpenHES
  license:
    name: BSL-1.0
    url: https://opensource.org/licenses/BSL-1.0
  contact:
    name: Cybros Labs team
    email: info@cybroslabs.com
    url: https://www.cybroslabs.com/index-en.html

components:
  schemas:
    # map[string](string|boolean|int|float|binary)
    AttributesSchema:
      type: object
      description: >
        Schema that describes a set of attributes and their values.
        The key is the property name and the value is the property value.
        The value can be of type string, integer, number, boolean, binary, or null.
      x-go-type: attribute.Attributes
      x-go-type-import:
        path: github.com/cybroslabs/hes-2-apis/openapi/openhes/attribute
      additionalProperties:
        anyOf:
          - type: string
          - type: integer
          - type: number
          - type: boolean
        nullable: true

    CommunicationUnitID:
      type: string
      format: uuid
      description: >
        The ID of the communication unit. The ID must be unique across all OpenHES components.

    DeviceID:
      type: string
      format: uuid
      description: >
        The ID of the device. The ID must be unique across all OpenHES components.

    DeviceGroupID:
      type: string
      format: uuid
      description: >
        The ID of the device group. The ID must be unique across all OpenHES components.

    CommunicationUnitSchema:
      type: object
      description: >
        Schema that describes communication unit details.
      properties:
        id:
          $ref: "#/components/schemas/CommunicationUnitID"
        externalID:
          type: string
          description: >
            The public ID of the communication unit.
          nullable: true
        name:
          type: string
          description: >
            The name of the communication unit.
          minLength: 1
        connectionInfo:
          $ref: "#/components/schemas/ConnectionInfoSchema"
      required:
        - id
        - name
        - connectionInfo

    CommunicationUnitListID:
      type: array
      description: >
        The list of communication unit IDs.
      items:
        $ref: "#/components/schemas/CommunicationUnitID"

    DeviceSchema:
      type: object
      description: >
        Schema that describes device details.
      properties:
        id:
          $ref: "#/components/schemas/DeviceID"
        externalID:
          type: string
          description: >
            The public ID of the device.
          nullable: true
        name:
          type: string
          description: >
            The name of the device.
          minLength: 1
        communicationUnitID:
          $ref: "#/components/schemas/CommunicationUnitListID"
        attributes:
          $ref: "#/components/schemas/AttributesSchema"
        timezone:
          type: string
          description: >
            The timezone of the device.
          nullable: true
      required:
        - id
        - name
        - communicationUnitID
        - attributes

    DeviceGroupSchema:
      type: object
      description: >
        Schema that describes device group details.
      properties:
        id:
          $ref: "#/components/schemas/DeviceGroupID"
        externalID:
          type: string
          description: >
            The public ID of the device group.
          nullable: true
        name:
          type: string
          description: >
            The name of the device group.
          minLength: 1
      required:
        - id
        - name

    ConnectionTypeTcpIpSchema:
      type: object
      description: >
        Schema that describes the TCP/IP connection.
      properties:
        type_tcp:
          type: integer
          minimum: 1
          maximum: 1
        host:
          type: string
          description: >
            The IP address or the hostname of the device.
        port:
          type: integer
          format: uint32
          description: >
            The port number of the device.
          minimum: 1
          maximum: 65535
      required:
        - type_tcp
        - host
        - port

    ConnectionTypePhoneLineSchema:
      type: object
      description: >
        Schema that describes the phone line (modem) connection.
      properties:
        type_modem:
          type: integer
          minimum: 1
          maximum: 1
        number:
          type: string
          description: >
            The phone number of the device.
          minLength: 1
        pool_id:
          type: string
          format: uuid
          description: >
            The modem pool ID.
      required:
        - type_modem
        - number
        - pool_id

    ConnectionTypeSerialMoxaSchema:
      type: object
      description: >
        Schema that describes the IP-to-serial connection using a Moxa device. The Moxa supports dynamic serial configuration changes via command connection.
      properties:
        type_serial_moxa:
          type: integer
          minimum: 1
          maximum: 1
        host:
          type: string
          description: >
            The IP address or the hostname of the device.
        dataPort:
          type: integer
          format: uint32
          description: >
            The port number of the device.
          minimum: 1
          maximum: 65535
        commandPort:
          type: integer
          format: uint32
          description: >
            The port number of the device.
          minimum: 1
          maximum: 65535
      required:
        - type_serial_moxa
        - host
        - dataPort
        - commandPort

    ConnectionTypeSerialDirectSchema:
      type: object
      description: >
        Schema that describes the direct IP to serial connection. It represents simple physical line without any on-demand confiration (e.g. speed or parity) as the configuration is statically set on the IP-to-serial device.
      properties:
        type_serial_direct:
          type: integer
          minimum: 1
          maximum: 1
        host:
          type: string
          description: >
            The IP address or the hostname of the device.
        port:
          type: integer
          format: uint32
          description: >
            The port number of the device.
          minimum: 1
          maximum: 65535
      required:
        - type_serial_direct
        - host
        - port

    ConnectionInfoSchema:
      allOf:
        - type: object
          properties:
            linkProtocol:
              $ref: "../driver/driver.yaml#/components/schemas/DataLinkProtocolSchema"
            customGroupingId:
              type: string
              description: >
                The custom group ID of the device.
              nullable: true
          required:
            - linkProtocol
        - oneOf:
          - $ref: "#/components/schemas/ConnectionTypeTcpIpSchema"
          - $ref: "#/components/schemas/ConnectionTypePhoneLineSchema"
          - $ref: "#/components/schemas/ConnectionTypeSerialMoxaSchema"
          - $ref: "#/components/schemas/ConnectionTypeSerialDirectSchema"

    ModemPoolSchema:
      type: object
      description: >
        Schema that describes modem pool details.
      properties:
        id:
          type: string
          format: uuid
          description: >
            The modem pool identifier. It is automatically generated during creation.
        name:
          type: string
          description: >
            The name of the modem pool.
      required:
        - id
        - name

    ModemSchema:
      type: object
      description: >
        Schema that describes modem details.
      properties:
        id:
          type: string
          format: uuid
          description: >
            The modem identifier. It is automatically generated during creation.
        name:
          type: string
          description: >
            The name of the modem.
        at_init:
          type: string
          description: >
            The modem initialization command.
          default: ""
        at_test:
          type: string
          description: >
            The modem test command.
          default: "AT"
        at_config:
          type: string
          description: >
            The modem configuration command.
          default: ""
        at_dial:
          type: string
          description: >
            The modem dial command.
          default: "ATD"
        at_hangup:
          type: string
          description: >
            The modem hangup command.
          default: "ATH"
        at_escape:
          type: string
          description: >
            The modem escape command.
          default: "+++"
        at_dsr:
          type: boolean
          description: >
            The modem DSR command.
          default: false
        connect_timeout:
          type: integer
          format: uint32
          description: >
            The modem connection timeout in seconds.
          minimum: 1
          default: 30
        connection:
          $ref: "#/components/schemas/ModemConnectionSchema"
      required:
        - id
        - name
        - at_init
        - at_test
        - at_config
        - at_dial
        - at_hangup
        - at_escape
        - at_dsr
        - connect_timeout
        - connection

    ModemConnectionSchema:
      description: >
        Schema that describes modem connection details. Currently only TCP/IP connection is supported.
      oneOf:
        - $ref: "#/components/schemas/ConnectionTypeTcpIpSchema"
