[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "platform API"
version = "1.0.0"
description = "Platform API for openHES and related applications"
readme = "README.md"
dependencies = []
requires-python = ">=3.6"
