openapi: "3.1.0"
info:
  version: 0.1.0
  title: Driver Data API models for OpenHES
  description: Driver Data API models for OpenHES
  license:
    name: BSL-1.0
    url: https://opensource.org/licenses/BSL-1.0
  contact:
    name: Cybros Labs team
    email: info@cybroslabs.com
    url: https://www.cybroslabs.com/index-en.html

components:
  schemas:
    GenericValueStatusSchema:
      type: object
      description: >
        Schema that describes the single value with its status and exponent.
      properties:
        status:
          type: integer
          format: int64
          description: >
            The status of the value.
        value:
          oneOf:
            - type: string
            - type: integer
              format: int64
            - type: number
              format: double
            - type: boolean
          description: >
            The value.
        exponent:
          type: integer
          format: int32
          description: >
            The exponent of the value.

    DeviceRegisterDataSchema:
      type: object
      description: >
        Schema that describes the register data.
      properties:
        timestamp:
          type: string
          format: date-time
          description: >
            The timestamp of the data.
        unit:
          type: string
          description: >
            The unit of the data.
        value:
          $ref: "#/components/schemas/GenericValueStatusSchema"

    DeviceProfileBlockValuesSchema:
      type: array
      description: >
        Schema that describes the list of profile values.
      items:
        $ref: "#/components/schemas/GenericValueStatusSchema"

    DeviceProfileBlockSchema:
      type: object
      description: >
        Schema that describes the single continuous block of profile data.
      properties:
        start:
          type: string
          format: date-time
          description: >
            The start time of the block.
        values:
          $ref: "#/components/schemas/DeviceProfileBlockValuesSchema"

    DeviceProfileBlocksSchema:
      type: array
      description: >
        Schema that describes the list of profile blocks.
      items:
        $ref: "#/components/schemas/DeviceProfileBlockSchema"

    DeviceRegistersDataSchema:
      type: array
      description: >
        Schema that describes the list of registers.
      items:
        $ref: "#/components/schemas/DeviceRegisterDataSchema"

    DeviceProfileDataSchema:
      type: object
      description: >
        Schema that describes the profile data.
      properties:
        blocks:
          $ref: "#/components/schemas/DeviceProfileBlocksSchema"
        unit:
          type: string
          description: >
            The unit of the profile data.
        period:
          type: integer
          format: int32
          description: >
            The period of the profile data in seconds.
      required:
        - blocks
        - unit
        - period
