openapi: "3.1.0"
info:
  version: 0.1.0
  title: RFC-7807 API models
  description: RFC-7807 API models
  license:
    name: BSL-1.0
    url: https://opensource.org/licenses/BSL-1.0
  contact:
    name: Cybros Labs team
    email: info@cybroslabs.com
    url: https://www.cybroslabs.com/index-en.html

components:
  schemas:
    ProblemDetailsSchema:
      type: object
      description: >
        Schema that carries the details of an error in an HTTP response.
        See https://datatracker.ietf.org/doc/html/rfc7807 for more information.
      examples:
        - type: "https://example.com/probs/not-found"
          title: "Resource not found"
          status: 404
          detail: "The requested resource was not found."
          instance: "/api/v1/pods/foo"
        - type: "https://example.com/probs/invalid-input"
          title: "Invalid input"
          status: 400
          detail: "The input provided is invalid."
          instance: "/api/v1/pods/foo"
        - type: "https://example.com/probs/internal-server-error"
          title: "Internal server error"
          status: 500
          detail: "An internal server error occurred."
          instance: "/api/v1/pods/foo"
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type.
          example: "https://example.com/probs/out-of-credit"
        title:
          type: string
          description: A human-readable summary of the problem type.
          example: "Out of credit"
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 403
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: "Your current balance is 30, but that costs 50."
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem.
          example: "/api/v1/pods/foo"
      required:
        - type
        - title
        - status
        - detail
        - instance
